name: CI/CD Pipeline with Monitoring

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  Linting-yaml:
    name: Linting-yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install yaml-lint
        run: sudo apt-get install -y yamllint

      - name: Lint YAML files
        run: yamllint ./**/*.yaml -d relaxed


  Linting-md:
    name: Linting-md
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Code
        uses: davidanson/markdownlint-cli2-action@v1
        with:
          config_path: .markdownlint.json
          globs: '**/*.{md,markdown}'

  unit-test:
    name: Unit-test
    runs-on: ubuntu-latest
    needs: [Linting-md,Linting-yaml]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: pytest tests/

  Gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run gitleaks for secrets scanning
        uses: zricethezav/gitleaks-action@v1
    
  SonarQube:
    name: SonarQube
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Check if SONAR_TOKEN is set
        run: |
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "Error: SONAR_TOKEN is not set!"
            exit 1
          fi

      - name: Run SonarCloud SAST
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.projectKey=zigzig234_Final-project
            -Dsonar.organization=zigzig234
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}

  Snyk:
    name: Snyk
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Snyk for dependency security scan
        uses: snyk/actions/python@master
        with:
          args: --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [Gitleaks,SonarQube,Snyk]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get install python3-pip
          python3 -m pip install requests ansible

      - name: Run Ansible Playbook to Build and Push Docker Image
        run: |
             ansible-playbook --vault-password-file <(echo ${{ secrets.VAULT_PASSWORD }}) -e @dockerhub_credentials.yml build-push-docker.yml 
